# Generated by Django 4.1.6 on 2023-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subject', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/about_us')),
            ],
            options={
                'verbose_name_plural': 'About us',
            },
        ),
    ]
