# Generated by Django 4.1.6 on 2023-02-05 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(5)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('situation', models.CharField(blank=True, choices=[('It was received', 'It was received'), ('In delivery', 'In delivery'), ('In manufacturing', 'In manufacturing')], max_length=200, null=True)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/orders/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
